services:
  web:
    build:
      context: .
      dockerfile: dockerfile
    env_file:
      - .env
    expose:
      - "8080"
    networks:
      - rede_compartilhada
    volumes:
      - media_data:/app/media
      - static_data:/app/staticfiles
    restart: unless-stopped

networks:
  rede_compartilhada:
    external: true

volumes:
  media_data:
  static_data: